// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectMonitor.Api.Database.Context;

#nullable disable

namespace ProjectMonitor.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221002203718_AddedErrorMessageFieldOnSystemData")]
    partial class AddedErrorMessageFieldOnSystemData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectMonitor.Api.Database.Models.ProjectHealth", b =>
                {
                    b.Property<string>("ProjectName")
                        .HasColumnType("text")
                        .HasColumnName("projectName");

                    b.Property<double>("CPUUsage")
                        .HasColumnType("double precision")
                        .HasColumnName("cpuUsage");

                    b.Property<bool>("ErrorMessageSent")
                        .HasColumnType("boolean")
                        .HasColumnName("errorMessageSent");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastUpdate");

                    b.Property<bool>("ProjectRunning")
                        .HasColumnType("boolean")
                        .HasColumnName("projectRunning");

                    b.Property<TimeSpan>("ProjectUptime")
                        .HasColumnType("interval")
                        .HasColumnName("projectUptime");

                    b.Property<long>("RAMUsage")
                        .HasColumnType("bigint")
                        .HasColumnName("ramUsage");

                    b.HasKey("ProjectName");

                    b.ToTable("ProjectHealth");
                });

            modelBuilder.Entity("ProjectMonitor.Api.Database.Models.SystemHealth", b =>
                {
                    b.Property<string>("SystemName")
                        .HasColumnType("text")
                        .HasColumnName("systemName");

                    b.Property<bool>("ErrorMessageSent")
                        .HasColumnType("boolean")
                        .HasColumnName("errorMessageSent");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastUpdate");

                    b.Property<TimeSpan>("SystemUptime")
                        .HasColumnType("interval")
                        .HasColumnName("systemUptime");

                    b.HasKey("SystemName");

                    b.ToTable("SystemHealth");
                });
#pragma warning restore 612, 618
        }
    }
}
