name: Build and Package Api project

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0

    - name: Build Docker Image
      run: |
        tree
        docker build -t projectmonitorapi -f ProjectMonitor/Dockerfile .
        
    - name: Save Docker Image
      run: |
        docker save projectmonitorapi > projectmonitorapi.tar

    - name: Upload Docker Image
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        source: projectmonitorapi.tar
        target: /root/Docker/
        
    - name: Stop And Remove Current Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
            docker stop projectmonitorapi || true && docker rm projectmonitorapi || true
    - name: Load New Docker Image
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker load -i /root/Docker/projectmonitorapi.tar

    - name: Start New Container
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          docker run -d -p 5000:80 --mount type=bind,source="${{ secrets.FILE_PATH }}",target=/app/Logs --env PMConnString='${{ secrets.ENV }}' --name projectmonitorapi projectmonitorapi:latest

    - name: Clean Up The Tar File
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          rm /root/Docker/projectmonitorapi.tar